#!/usr/bin/env node
// AGENT-TRACE: Keeps apps/api/.env in sync with local dev infra (Supabase + Redis + Portal).
// This script is invoked by scripts/dev.sh before the NestJS API is started.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const REPO_ROOT = process.cwd();
const PORTAL_ENV_PATH = resolve(REPO_ROOT, "apps/portal/.env");
const PORTAL_ENV_LOCAL_PATH = resolve(REPO_ROOT, "apps/portal/.env.local");
const API_ENV_PATH = resolve(REPO_ROOT, "apps/api/.env");
const API_ENV_EXAMPLE_PATH = resolve(REPO_ROOT, "apps/api/.env.example");

const DEFAULT_API_PORT = "3004";

// Keys that are always rewritten by the generator so the orchestrator stays
// consistent (users can override via API_PORT / API_CORS_ORIGIN env vars).
const FORCED_KEYS = new Set(["PORT", "CORS_ORIGIN"]);

/**
 * Read a file as UTF-8; return empty string if missing.
 */
async function readEnvFile(path) {
  try {
    return await readFile(path, "utf8");
  } catch {
    return "";
  }
}

/**
 * Parse KEY=VALUE lines into a Map. Preserves the raw value after the first `=`.
 * Comments and blank lines are ignored for lookup but kept during serialization.
 */
function parseEnv(text) {
  const map = new Map();
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (match) {
      map.set(match[1], match[2]);
    }
  }
  return map;
}

/**
 * Read the portal env, falling back to the example template if needed.
 */
async function loadPortalEnv() {
  const text =
    (await readEnvFile(PORTAL_ENV_LOCAL_PATH)) ||
    (await readEnvFile(PORTAL_ENV_PATH)) ||
    (await readEnvFile(PORTAL_ENV_PATH.replace(".env", ".env.example")));
  return parseEnv(text);
}

/**
 * Build the canonical values for the API env from the portal env.
 */
function buildApiDefaults(portal) {
  const supabaseUrl =
    portal.get("SUPABASE_URL") ||
    portal.get("NEXT_PUBLIC_SUPABASE_URL") ||
    "http://127.0.0.1:54321";
  const anonKey =
    portal.get("SUPABASE_ANON_KEY") ||
    portal.get("NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    "your-anon-key";
  const serviceKey =
    portal.get("SUPABASE_SERVICE_KEY") || "your-service-role-key";

  const apiPort = process.env.API_PORT || DEFAULT_API_PORT;
  const corsOrigin = process.env.API_CORS_ORIGIN || "http://localhost:3000";

  return new Map([
    ["NODE_ENV", "development"],
    ["PORT", apiPort],
    ["SUPABASE_URL", supabaseUrl],
    ["SUPABASE_SERVICE_KEY", serviceKey],
    ["NEXT_PUBLIC_SUPABASE_URL", supabaseUrl],
    ["NEXT_PUBLIC_SUPABASE_ANON_KEY", anonKey],
    ["REDIS_URL", "redis://localhost:6379"],
    ["OLLAMA_URL", portal.get("OLLAMA_URL") || "http://localhost:5243"],
    ["CORS_ORIGIN", corsOrigin],
    ["SENTRY_DSN", ""],
    ["OTEL_EXPORTER_OTLP_ENDPOINT", ""],
    ["DISABLE_RATE_LIMIT", "false"],
    ["RATE_LIMIT_IP_WHITELIST", "127.0.0.1,::1,::ffff:127.0.0.1"],
    ["TRUST_PROXY", "true"],
    ["INTERNAL_API_SECRET", ""],
  ]);
}

/**
 * Returns true if a value is obviously a placeholder that should be replaced.
 */
function isPlaceholder(value) {
  if (!value) return true;
  const lower = value.toLowerCase();
  return (
    lower.includes("your-") ||
    lower.includes("todo") ||
    lower.includes("changeme") ||
    lower === "..." ||
    lower === "placeholder"
  );
}

/**
 * Merge the existing API env file with the generated defaults.
 * Preserves comments and existing non-placeholder values.
 */
function mergeEnvFile(existingText, defaults) {
  const lines = existingText.split(/\r?\n/);
  const seen = new Set();
  const out = [];

  for (const line of lines) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) {
      out.push(line);
      continue;
    }

    const key = match[1];
    let value = match[2];
    seen.add(key);

    if (defaults.has(key) && (FORCED_KEYS.has(key) || isPlaceholder(value))) {
      value = defaults.get(key);
    }

    out.push(`${key}=${value}`);
  }

  // Append any missing defaults at the end with a small header.
  const missing = [];
  for (const [key, value] of defaults) {
    if (!seen.has(key)) {
      missing.push(`${key}=${value}`);
    }
  }

  if (missing.length > 0) {
    out.push("");
    out.push("# ── generated by scripts/generate-api-env.mjs ──");
    out.push(...missing);
  }

  // Ensure exactly one trailing newline.
  return out.join("\n").replace(/\n*$/, "\n");
}

/**
 * Seed a fresh API .env from the example template when no existing file is present.
 */
async function seedFromExample(defaults) {
  let example = await readEnvFile(API_ENV_EXAMPLE_PATH);
  if (!example) {
    // Fallback to a minimal template if the example is missing.
    example = Array.from(defaults.entries())
      .map(([key, value]) => `${key}=${value}`)
      .join("\n");
  }
  return mergeEnvFile(example, defaults);
}

async function main() {
  const portal = await loadPortalEnv();
  const defaults = buildApiDefaults(portal);

  const existing = await readEnvFile(API_ENV_PATH);
  const merged = existing
    ? mergeEnvFile(existing, defaults)
    : await seedFromExample(defaults);

  await writeFile(API_ENV_PATH, merged);

  // Print the resolved API port so the orchestrator can read it back if needed.
  const portLine = merged
    .split(/\r?\n/)
    .find((line) => line.match(/^PORT\s*=\s*(.*)$/));
  const port = portLine ? portLine.split("=")[1].trim() : DEFAULT_API_PORT;
  process.stdout.write(`API_PORT=${port}\n`);
}

main().catch((error) => {
  console.error("[generate-api-env] failed:", error.message);
  process.exit(1);
});
