#!/usr/bin/env node
/**
 * Generate apps/api/.env from the portal environment.
 *
 * Usage:
 *   node scripts/generate-api-env.mjs
 *
 * Reads apps/portal/.env.local, extracts Supabase/Redis/Ollama keys,
 * and writes apps/api/.env with the correct PORT and CORS_ORIGIN.
 * Idempotent — safe to run on every `pnpm dev`.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const PORTAL_ENV = resolve(REPO_ROOT, "apps/portal/.env.local");
const API_ENV = resolve(REPO_ROOT, "apps/api/.env");

function loadEnv(path) {
  const env = {};
  if (!existsSync(path)) return env;
  const content = readFileSync(path, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    env[key] = value;
  }
  return env;
}

const portalEnv = loadEnv(PORTAL_ENV);

const apiEnv = {
  PORT: process.env.API_PORT || "3004",
  CORS_ORIGIN: `http://localhost:${process.env.PORT || "3000"}`,
  NODE_ENV: "development",
  SUPABASE_URL:
    portalEnv.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || "http://127.0.0.1:54321",
  SUPABASE_ANON_KEY:
    portalEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE_ROLE_KEY:
    portalEnv.SUPABASE_SERVICE_ROLE_KEY ||
    portalEnv.SUPABASE_SERVICE_KEY ||
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    "",
  REDIS_URL: portalEnv.REDIS_URL || process.env.REDIS_URL || "redis://localhost:6379",
  OLLAMA_BASE_URL: portalEnv.OLLAMA_BASE_URL || process.env.OLLAMA_BASE_URL || "",
};

const lines = [
  "# Auto-generated by scripts/generate-api-env.mjs — do not hand-edit",
  `PORT=${apiEnv.PORT}`,
  `CORS_ORIGIN=${apiEnv.CORS_ORIGIN}`,
  `NODE_ENV=${apiEnv.NODE_ENV}`,
  `SUPABASE_URL=${apiEnv.SUPABASE_URL}`,
  `SUPABASE_ANON_KEY=${apiEnv.SUPABASE_ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${apiEnv.SUPABASE_SERVICE_ROLE_KEY}`,
  `REDIS_URL=${apiEnv.REDIS_URL}`,
  `OLLAMA_BASE_URL=${apiEnv.OLLAMA_BASE_URL}`,
  "",
];

writeFileSync(API_ENV, lines.join("\n"), "utf-8");
console.log(`[generate-api-env] Wrote ${API_ENV}`);
