/**
 * generated.ts — AUTO-GENERATED. DO NOT EDIT.
 *
 * Generated by: packages/theme/scripts/generate-tokens.mjs
 * Source:       packages/theme/src/css/variables.css
 *
 * Re-run with: node packages/theme/scripts/generate-tokens.mjs
 * Or via Turbo: pnpm --filter @repo/theme codegen
 *
 * This file provides typed `var(--token)` references for use in:
 * - Framer Motion style props
 * - Canvas/WebGL drawing
 * - Runtime style injection
 *
 * For static Tailwind usage, use the className utilities instead
 * (e.g. `text-[var(--text-heading)]` or `shadow-card`).
 */

export const tokens = {
  color: {
    bg: {
      primary: "var(--bg-primary)",
      secondary: "var(--bg-secondary)",
      tertiary: "var(--bg-tertiary)",
    },
    border: {
      subtle: "var(--border-subtle)",
      default: "var(--border-default)",
      emphasis: "var(--border-emphasis)",
    },
    text: {
      muted: "var(--text-muted)",
      secondary: "var(--text-secondary)",
      body: "var(--text-body)",
      primary: "var(--text-primary)",
      heading: "var(--text-heading)",
      onGlass: "var(--text-on-glass)",
      onGlassMuted: "var(--text-on-glass-muted)",
      onDarkGlass: "var(--text-on-dark-glass)",
      onDarkGlassMuted: "var(--text-on-dark-glass-muted)",
      onGlassVideo: "var(--text-on-glass-video)",
      onGlassVideoMuted: "var(--text-on-glass-video-muted)",
    },
    accent: {
      red: "var(--accent-red)",
      blue: "var(--accent-blue)",
      green: "var(--accent-green)",
      electricBlue: "var(--accent-electric-blue)",
      electricBlueHover: "var(--accent-electric-blue-hover)",
      electricBlueSubtle: "var(--accent-electric-blue-subtle)",
      electricBlueBorder: "var(--accent-electric-blue-border)",
      mint: "var(--accent-mint)",
      mintHover: "var(--accent-mint-hover)",
      mintSubtle: "var(--accent-mint-subtle)",
      mintBorder: "var(--accent-mint-border)",
      amber: "var(--accent-amber)",
      amberHover: "var(--accent-amber-hover)",
      amberSubtle: "var(--accent-amber-subtle)",
      amberBorder: "var(--accent-amber-border)",
      cyan: "var(--accent-cyan)",
      indigo: "var(--accent-indigo)",
      violet: "var(--accent-violet)",
      alert: "var(--accent-alert)",
      emerald: "var(--accent-emerald)",
      foreground: "var(--accent-foreground)",
    },
    mac: {
      red: "var(--mac-red)",
      yellow: "var(--mac-yellow)",
      green: "var(--mac-green)",
      menuBarHeight: "var(--mac-menu-bar-height)",
    },
    glass: {
      surface: "var(--glass-surface)",
      surfaceHover: "var(--glass-surface-hover)",
      surfaceStrong: "var(--glass-surface-strong)",
      border: "var(--glass-border)",
      borderTop: "var(--glass-border-top)",
      videoSurface: "var(--glass-video-surface)",
      videoSurfaceHover: "var(--glass-video-surface-hover)",
      videoSurfaceStrong: "var(--glass-video-surface-strong)",
      videoBackdrop: "var(--glass-video-backdrop)",
      videoBorder: "var(--glass-video-border)",
      videoBorderBottom: "var(--glass-video-border-bottom)",
      videoSheen: "var(--glass-video-sheen)",
      videoRadius: "var(--glass-video-radius)",
      premiumBackdrop: "var(--glass-premium-backdrop)",
      premiumBorder: "var(--glass-premium-border)",
      premiumRadius: "var(--glass-premium-radius)",
    },
    vibrancy: {
      surface: "var(--vibrancy-surface)",
      border: "var(--vibrancy-border)",
    },
  },
  shadow: {
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
  },
  radius: {},
  wave: {
    intensity: "0.2",
    speedMult: "0.5",
    amplScale: "0.4",
    opacity: "0.25",
  },
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.color;
export type ShadowTokens = typeof tokens.shadow;
export type RadiusTokens = typeof tokens.radius;
