/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  arch0: {
    key: '{arch0}',
    value: '#ffffff',
    type: 'color',
    description: 'macOS pure white background',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#ffffff',
      type: 'color',
      description: 'macOS pure white background',
      key: '{arch0}',
    },
    name: 'Arch0',
    attributes: {
      category: 'arch0',
    },
    path: ['arch0'],
  },
  arch1: {
    key: '{arch1}',
    value: '#ffffff',
    type: 'color',
    description: 'elevated surface / card',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#ffffff',
      type: 'color',
      description: 'elevated surface / card',
      key: '{arch1}',
    },
    name: 'Arch1',
    attributes: {
      category: 'arch1',
    },
    path: ['arch1'],
  },
  arch2: {
    key: '{arch2}',
    value: '#e8e8ed',
    type: 'color',
    description: 'sunken / input bg',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#e8e8ed',
      type: 'color',
      description: 'sunken / input bg',
      key: '{arch2}',
    },
    name: 'Arch2',
    attributes: {
      category: 'arch2',
    },
    path: ['arch2'],
  },
  arch3: {
    key: '{arch3}',
    value: '#d2d2d7',
    type: 'color',
    description: 'pressed / deeply sunken',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#d2d2d7',
      type: 'color',
      description: 'pressed / deeply sunken',
      key: '{arch3}',
    },
    name: 'Arch3',
    attributes: {
      category: 'arch3',
    },
    path: ['arch3'],
  },
  arch4: {
    key: '{arch4}',
    value: '#0000000f',
    type: 'color',
    description: 'border subtle',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.06)',
      type: 'color',
      description: 'border subtle',
      key: '{arch4}',
    },
    name: 'Arch4',
    attributes: {
      category: 'arch4',
    },
    path: ['arch4'],
  },
  arch5: {
    key: '{arch5}',
    value: '#0000001f',
    type: 'color',
    description: 'border default',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.12)',
      type: 'color',
      description: 'border default',
      key: '{arch5}',
    },
    name: 'Arch5',
    attributes: {
      category: 'arch5',
    },
    path: ['arch5'],
  },
  arch6: {
    key: '{arch6}',
    value: '#00000033',
    type: 'color',
    description: 'border emphasis',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.2)',
      type: 'color',
      description: 'border emphasis',
      key: '{arch6}',
    },
    name: 'Arch6',
    attributes: {
      category: 'arch6',
    },
    path: ['arch6'],
  },
  arch7: {
    key: '{arch7}',
    value: '#0000004d',
    type: 'color',
    description: 'border strong',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.3)',
      type: 'color',
      description: 'border strong',
      key: '{arch7}',
    },
    name: 'Arch7',
    attributes: {
      category: 'arch7',
    },
    path: ['arch7'],
  },
  arch8: {
    key: '{arch8}',
    value: '#a1a1a6',
    type: 'color',
    description: 'muted / placeholder',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#a1a1a6',
      type: 'color',
      description: 'muted / placeholder',
      key: '{arch8}',
    },
    name: 'Arch8',
    attributes: {
      category: 'arch8',
    },
    path: ['arch8'],
  },
  arch9: {
    key: '{arch9}',
    value: '#6e6e73',
    type: 'color',
    description: 'secondary / caption',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#6e6e73',
      type: 'color',
      description: 'secondary / caption',
      key: '{arch9}',
    },
    name: 'Arch9',
    attributes: {
      category: 'arch9',
    },
    path: ['arch9'],
  },
  arch10: {
    key: '{arch10}',
    value: '#3a3a3c',
    type: 'color',
    description: 'body',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#3a3a3c',
      type: 'color',
      description: 'body',
      key: '{arch10}',
    },
    name: 'Arch10',
    attributes: {
      category: 'arch10',
    },
    path: ['arch10'],
  },
  arch11: {
    key: '{arch11}',
    value: '#1d1d1f',
    type: 'color',
    description: 'heading / primary',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#1d1d1f',
      type: 'color',
      description: 'heading / primary',
      key: '{arch11}',
    },
    name: 'Arch11',
    attributes: {
      category: 'arch11',
    },
    path: ['arch11'],
  },
  arch12: {
    key: '{arch12}',
    value: '#d22118',
    type: 'color',
    description: 'red — error / danger',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#d22118',
      type: 'color',
      description: 'red — error / danger',
      key: '{arch12}',
    },
    name: 'Arch12',
    attributes: {
      category: 'arch12',
    },
    path: ['arch12'],
  },
  arch13: {
    key: '{arch13}',
    value: '#1c1c1e',
    type: 'color',
    description: 'deep charcoal — replaced blue',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#1c1c1e',
      type: 'color',
      description: 'deep charcoal — replaced blue',
      key: '{arch13}',
    },
    name: 'Arch13',
    attributes: {
      category: 'arch13',
    },
    path: ['arch13'],
  },
  arch14: {
    key: '{arch14}',
    value: '#34c759',
    type: 'color',
    description: 'green — success',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#34c759',
      type: 'color',
      description: 'green — success',
      key: '{arch14}',
    },
    name: 'Arch14',
    attributes: {
      category: 'arch14',
    },
    path: ['arch14'],
  },
  arch15: {
    key: '{arch15}',
    value: '#1c1c1e',
    type: 'color',
    description: 'deep charcoal — macOS system blue',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#1c1c1e',
      type: 'color',
      description: 'deep charcoal — macOS system blue',
      key: '{arch15}',
    },
    name: 'Arch15',
    attributes: {
      category: 'arch15',
    },
    path: ['arch15'],
  },
  'mac-red': {
    key: '{mac-red}',
    value: '#ff5f56',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#ff5f56',
      type: 'color',
      key: '{mac-red}',
    },
    name: 'MacRed',
    attributes: {
      category: 'mac-red',
    },
    path: ['mac-red'],
  },
  'mac-yellow': {
    key: '{mac-yellow}',
    value: '#ffbd2e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#ffbd2e',
      type: 'color',
      key: '{mac-yellow}',
    },
    name: 'MacYellow',
    attributes: {
      category: 'mac-yellow',
    },
    path: ['mac-yellow'],
  },
  'mac-green': {
    key: '{mac-green}',
    value: '#27c93f',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#27c93f',
      type: 'color',
      key: '{mac-green}',
    },
    name: 'MacGreen',
    attributes: {
      category: 'mac-green',
    },
    path: ['mac-green'],
  },
  'mac-menu-bar-height': {
    key: '{mac-menu-bar-height}',
    value: '28px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '28px',
      type: 'dimension',
      key: '{mac-menu-bar-height}',
    },
    name: 'MacMenuBarHeight',
    attributes: {
      category: 'mac-menu-bar-height',
    },
    path: ['mac-menu-bar-height'],
  },
  bg: {
    primary: {
      key: '{bg.primary}',
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch0}',
        type: 'color',
        key: '{bg.primary}',
      },
      name: 'BgPrimary',
      attributes: {
        category: 'bg',
        type: 'primary',
      },
      path: ['bg', 'primary'],
    },
    secondary: {
      key: '{bg.secondary}',
      value: '#ffffff',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch1}',
        type: 'color',
        key: '{bg.secondary}',
      },
      name: 'BgSecondary',
      attributes: {
        category: 'bg',
        type: 'secondary',
      },
      path: ['bg', 'secondary'],
    },
    tertiary: {
      key: '{bg.tertiary}',
      value: '#e8e8ed',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch2}',
        type: 'color',
        key: '{bg.tertiary}',
      },
      name: 'BgTertiary',
      attributes: {
        category: 'bg',
        type: 'tertiary',
      },
      path: ['bg', 'tertiary'],
    },
  },
  border: {
    key: '{border}',
    value: '240 6% 87%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 87%',
      type: 'color',
      key: '{border}',
    },
    name: 'Border',
    attributes: {
      category: 'border',
    },
    path: ['border'],
  },
  'border-subtle': {
    key: '{border-subtle}',
    value: '#0000000f',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch4}',
      type: 'color',
      key: '{border-subtle}',
    },
    name: 'BorderSubtle',
    attributes: {
      category: 'border-subtle',
    },
    path: ['border-subtle'],
  },
  'border-default': {
    key: '{border-default}',
    value: '#0000001f',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch5}',
      type: 'color',
      key: '{border-default}',
    },
    name: 'BorderDefault',
    attributes: {
      category: 'border-default',
    },
    path: ['border-default'],
  },
  'border-emphasis': {
    key: '{border-emphasis}',
    value: '#00000033',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch6}',
      type: 'color',
      key: '{border-emphasis}',
    },
    name: 'BorderEmphasis',
    attributes: {
      category: 'border-emphasis',
    },
    path: ['border-emphasis'],
  },
  text: {
    muted: {
      key: '{text.muted}',
      value: '#a1a1a6',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch8}',
        type: 'color',
        key: '{text.muted}',
      },
      name: 'TextMuted',
      attributes: {
        category: 'text',
        type: 'muted',
      },
      path: ['text', 'muted'],
    },
    secondary: {
      key: '{text.secondary}',
      value: '#6e6e73',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch9}',
        type: 'color',
        key: '{text.secondary}',
      },
      name: 'TextSecondary',
      attributes: {
        category: 'text',
        type: 'secondary',
      },
      path: ['text', 'secondary'],
    },
    body: {
      key: '{text.body}',
      value: '#3a3a3c',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch10}',
        type: 'color',
        key: '{text.body}',
      },
      name: 'TextBody',
      attributes: {
        category: 'text',
        type: 'body',
      },
      path: ['text', 'body'],
    },
    primary: {
      key: '{text.primary}',
      value: '#3a3a3c',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch10}',
        type: 'color',
        key: '{text.primary}',
      },
      name: 'TextPrimary',
      attributes: {
        category: 'text',
        type: 'primary',
      },
      path: ['text', 'primary'],
    },
    heading: {
      key: '{text.heading}',
      value: '#1d1d1f',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '{arch11}',
        type: 'color',
        key: '{text.heading}',
      },
      name: 'TextHeading',
      attributes: {
        category: 'text',
        type: 'heading',
      },
      path: ['text', 'heading'],
    },
  },
  'accent-red': {
    key: '{accent-red}',
    value: '#d22118',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#d22118',
      type: 'color',
      key: '{accent-red}',
    },
    name: 'AccentRed',
    attributes: {
      category: 'accent-red',
    },
    path: ['accent-red'],
  },
  'accent-charcoal': {
    key: '{accent-charcoal}',
    value: '#1c1c1e',
    type: 'color',
    description: 'Canonical brand interactive — deep charcoal',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch13}',
      type: 'color',
      description: 'Canonical brand interactive — deep charcoal',
      key: '{accent-charcoal}',
    },
    name: 'AccentCharcoal',
    attributes: {
      category: 'accent-charcoal',
    },
    path: ['accent-charcoal'],
  },
  'accent-blue': {
    key: '{accent-blue}',
    value: '#1c1c1e',
    type: 'color',
    description: '@deprecated alias — use accent-charcoal',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch13}',
      type: 'color',
      description: '@deprecated alias — use accent-charcoal',
      key: '{accent-blue}',
    },
    name: 'AccentBlue',
    attributes: {
      category: 'accent-blue',
    },
    path: ['accent-blue'],
  },
  'accent-green': {
    key: '{accent-green}',
    value: '#34c759',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch14}',
      type: 'color',
      key: '{accent-green}',
    },
    name: 'AccentGreen',
    attributes: {
      category: 'accent-green',
    },
    path: ['accent-green'],
  },
  'accent-alert': {
    key: '{accent-alert}',
    value: '#d22118',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#d22118',
      type: 'color',
      key: '{accent-alert}',
    },
    name: 'AccentAlert',
    attributes: {
      category: 'accent-alert',
    },
    path: ['accent-alert'],
  },
  'accent-cyan': {
    key: '{accent-cyan}',
    value: '#1c1c1e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch15}',
      type: 'color',
      key: '{accent-cyan}',
    },
    name: 'AccentCyan',
    attributes: {
      category: 'accent-cyan',
    },
    path: ['accent-cyan'],
  },
  'accent-emerald': {
    key: '{accent-emerald}',
    value: '#34c759',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch14}',
      type: 'color',
      key: '{accent-emerald}',
    },
    name: 'AccentEmerald',
    attributes: {
      category: 'accent-emerald',
    },
    path: ['accent-emerald'],
  },
  'accent-indigo': {
    key: '{accent-indigo}',
    value: '#1c1c1e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch15}',
      type: 'color',
      key: '{accent-indigo}',
    },
    name: 'AccentIndigo',
    attributes: {
      category: 'accent-indigo',
    },
    path: ['accent-indigo'],
  },
  'accent-violet': {
    key: '{accent-violet}',
    value: '#1c1c1e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '{arch15}',
      type: 'color',
      key: '{accent-violet}',
    },
    name: 'AccentViolet',
    attributes: {
      category: 'accent-violet',
    },
    path: ['accent-violet'],
  },
  success: {
    key: '{success}',
    value: '#34c759',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#34c759',
      type: 'color',
      key: '{success}',
    },
    name: 'Success',
    attributes: {
      category: 'success',
    },
    path: ['success'],
  },
  'success-foreground': {
    key: '{success-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{success-foreground}',
    },
    name: 'SuccessForeground',
    attributes: {
      category: 'success-foreground',
    },
    path: ['success-foreground'],
  },
  warning: {
    key: '{warning}',
    value: '#1c1c1e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#1c1c1e',
      type: 'color',
      key: '{warning}',
    },
    name: 'Warning',
    attributes: {
      category: 'warning',
    },
    path: ['warning'],
  },
  'warning-foreground': {
    key: '{warning-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{warning-foreground}',
    },
    name: 'WarningForeground',
    attributes: {
      category: 'warning-foreground',
    },
    path: ['warning-foreground'],
  },
  danger: {
    key: '{danger}',
    value: '#d22118',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#d22118',
      type: 'color',
      key: '{danger}',
    },
    name: 'Danger',
    attributes: {
      category: 'danger',
    },
    path: ['danger'],
  },
  'danger-foreground': {
    key: '{danger-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{danger-foreground}',
    },
    name: 'DangerForeground',
    attributes: {
      category: 'danger-foreground',
    },
    path: ['danger-foreground'],
  },
  info: {
    key: '{info}',
    value: '#1c1c1e',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '#1c1c1e',
      type: 'color',
      key: '{info}',
    },
    name: 'Info',
    attributes: {
      category: 'info',
    },
    path: ['info'],
  },
  'info-foreground': {
    key: '{info-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{info-foreground}',
    },
    name: 'InfoForeground',
    attributes: {
      category: 'info-foreground',
    },
    path: ['info-foreground'],
  },
  glass: {
    surface: {
      key: '{glass.surface}',
      value: '#ffffffb3',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(255, 255, 255, 0.7)',
        type: 'color',
        key: '{glass.surface}',
      },
      name: 'GlassSurface',
      attributes: {
        category: 'glass',
        type: 'surface',
      },
      path: ['glass', 'surface'],
    },
    'surface-hover': {
      key: '{glass.surface-hover}',
      value: '#ffffffd9',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(255, 255, 255, 0.85)',
        type: 'color',
        key: '{glass.surface-hover}',
      },
      name: 'GlassSurfaceHover',
      attributes: {
        category: 'glass',
        type: 'surface-hover',
      },
      path: ['glass', 'surface-hover'],
    },
    'surface-strong': {
      key: '{glass.surface-strong}',
      value: '#ffffffeb',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(255, 255, 255, 0.92)',
        type: 'color',
        key: '{glass.surface-strong}',
      },
      name: 'GlassSurfaceStrong',
      attributes: {
        category: 'glass',
        type: 'surface-strong',
      },
      path: ['glass', 'surface-strong'],
    },
    border: {
      key: '{glass.border}',
      value: '#ffffff26',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(255, 255, 255, 0.15)',
        type: 'color',
        key: '{glass.border}',
      },
      name: 'GlassBorder',
      attributes: {
        category: 'glass',
        type: 'border',
      },
      path: ['glass', 'border'],
    },
    'border-top': {
      key: '{glass.border-top}',
      value: '#ffffff40',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(255, 255, 255, 0.25)',
        type: 'color',
        key: '{glass.border-top}',
      },
      name: 'GlassBorderTop',
      attributes: {
        category: 'glass',
        type: 'border-top',
      },
      path: ['glass', 'border-top'],
    },
    'border-gradient': {
      key: '{glass.border-gradient}',
      value: 'linear-gradient(to bottom, rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.3))',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'linear-gradient(to bottom, rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.3))',
        type: 'color',
        key: '{glass.border-gradient}',
      },
      name: 'GlassBorderGradient',
      attributes: {
        category: 'glass',
        type: 'border-gradient',
      },
      path: ['glass', 'border-gradient'],
    },
    text: {
      key: '{glass.text}',
      value: '#0a0a14eb',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(10, 10, 20, 0.92)',
        type: 'color',
        key: '{glass.text}',
      },
      name: 'GlassText',
      attributes: {
        category: 'glass',
        type: 'text',
      },
      path: ['glass', 'text'],
    },
    'text-muted': {
      key: '{glass.text-muted}',
      value: '#0a0a148c',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(10, 10, 20, 0.55)',
        type: 'color',
        key: '{glass.text-muted}',
      },
      name: 'GlassTextMuted',
      attributes: {
        category: 'glass',
        type: 'text-muted',
      },
      path: ['glass', 'text-muted'],
    },
    vibrancy: {
      key: '{glass.vibrancy}',
      value: '#f6f6fad1',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(246, 246, 250, 0.82)',
        type: 'color',
        key: '{glass.vibrancy}',
      },
      name: 'GlassVibrancy',
      attributes: {
        category: 'glass',
        type: 'vibrancy',
      },
      path: ['glass', 'vibrancy'],
    },
    shadow: {
      key: '{glass.shadow}',
      value:
        '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 20px 25px -5px rgba(0, 0, 0, 0.03), inset 0 1px 0 0 rgba(255, 255, 255, 0.8)',
      type: 'shadow',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value:
          '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 20px 25px -5px rgba(0, 0, 0, 0.03), inset 0 1px 0 0 rgba(255, 255, 255, 0.8)',
        type: 'shadow',
        key: '{glass.shadow}',
      },
      name: 'GlassShadow',
      attributes: {
        category: 'glass',
        type: 'shadow',
      },
      path: ['glass', 'shadow'],
    },
  },
  'text-on-glass': {
    key: '{text-on-glass}',
    value: '#0a0a14eb',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(10, 10, 20, 0.92)',
      type: 'color',
      key: '{text-on-glass}',
    },
    name: 'TextOnGlass',
    attributes: {
      category: 'text-on-glass',
    },
    path: ['text-on-glass'],
  },
  'text-on-glass-muted': {
    key: '{text-on-glass-muted}',
    value: '#0a0a148c',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(10, 10, 20, 0.55)',
      type: 'color',
      key: '{text-on-glass-muted}',
    },
    name: 'TextOnGlassMuted',
    attributes: {
      category: 'text-on-glass-muted',
    },
    path: ['text-on-glass-muted'],
  },
  vibrancy: {
    surface: {
      key: '{vibrancy.surface}',
      value: '#f6f6fad1',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(246, 246, 250, 0.82)',
        type: 'color',
        key: '{vibrancy.surface}',
      },
      name: 'VibrancySurface',
      attributes: {
        category: 'vibrancy',
        type: 'surface',
      },
      path: ['vibrancy', 'surface'],
    },
    border: {
      key: '{vibrancy.border}',
      value: '#0000000f',
      type: 'color',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'rgba(0, 0, 0, 0.06)',
        type: 'color',
        key: '{vibrancy.border}',
      },
      name: 'VibrancyBorder',
      attributes: {
        category: 'vibrancy',
        type: 'border',
      },
      path: ['vibrancy', 'border'],
    },
  },
  'overlay-dim': {
    key: '{overlay-dim}',
    value: '#00000005',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.02)',
      type: 'color',
      key: '{overlay-dim}',
    },
    name: 'OverlayDim',
    attributes: {
      category: 'overlay-dim',
    },
    path: ['overlay-dim'],
  },
  'overlay-subtle': {
    key: '{overlay-subtle}',
    value: '#0000000a',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.04)',
      type: 'color',
      key: '{overlay-subtle}',
    },
    name: 'OverlaySubtle',
    attributes: {
      category: 'overlay-subtle',
    },
    path: ['overlay-subtle'],
  },
  'overlay-medium': {
    key: '{overlay-medium}',
    value: '#0000000f',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: 'rgba(0, 0, 0, 0.06)',
      type: 'color',
      key: '{overlay-medium}',
    },
    name: 'OverlayMedium',
    attributes: {
      category: 'overlay-medium',
    },
    path: ['overlay-medium'],
  },
  background: {
    key: '{background}',
    value: '240 5% 96%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 96%',
      type: 'color',
      key: '{background}',
    },
    name: 'Background',
    attributes: {
      category: 'background',
    },
    path: ['background'],
  },
  foreground: {
    key: '{foreground}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{foreground}',
    },
    name: 'Foreground',
    attributes: {
      category: 'foreground',
    },
    path: ['foreground'],
  },
  card: {
    key: '{card}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{card}',
    },
    name: 'Card',
    attributes: {
      category: 'card',
    },
    path: ['card'],
  },
  'card-foreground': {
    key: '{card-foreground}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{card-foreground}',
    },
    name: 'CardForeground',
    attributes: {
      category: 'card-foreground',
    },
    path: ['card-foreground'],
  },
  popover: {
    key: '{popover}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{popover}',
    },
    name: 'Popover',
    attributes: {
      category: 'popover',
    },
    path: ['popover'],
  },
  'popover-foreground': {
    key: '{popover-foreground}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{popover-foreground}',
    },
    name: 'PopoverForeground',
    attributes: {
      category: 'popover-foreground',
    },
    path: ['popover-foreground'],
  },
  primary: {
    key: '{primary}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{primary}',
    },
    name: 'Primary',
    attributes: {
      category: 'primary',
    },
    path: ['primary'],
  },
  'primary-foreground': {
    key: '{primary-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{primary-foreground}',
    },
    name: 'PrimaryForeground',
    attributes: {
      category: 'primary-foreground',
    },
    path: ['primary-foreground'],
  },
  secondary: {
    key: '{secondary}',
    value: '240 5% 91%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 91%',
      type: 'color',
      key: '{secondary}',
    },
    name: 'Secondary',
    attributes: {
      category: 'secondary',
    },
    path: ['secondary'],
  },
  'secondary-foreground': {
    key: '{secondary-foreground}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{secondary-foreground}',
    },
    name: 'SecondaryForeground',
    attributes: {
      category: 'secondary-foreground',
    },
    path: ['secondary-foreground'],
  },
  muted: {
    key: '{muted}',
    value: '240 5% 91%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 91%',
      type: 'color',
      key: '{muted}',
    },
    name: 'Muted',
    attributes: {
      category: 'muted',
    },
    path: ['muted'],
  },
  'muted-foreground': {
    key: '{muted-foreground}',
    value: '240 3% 44%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 3% 44%',
      type: 'color',
      key: '{muted-foreground}',
    },
    name: 'MutedForeground',
    attributes: {
      category: 'muted-foreground',
    },
    path: ['muted-foreground'],
  },
  accent: {
    key: '{accent}',
    value: '240 5% 91%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 91%',
      type: 'color',
      key: '{accent}',
    },
    name: 'Accent',
    attributes: {
      category: 'accent',
    },
    path: ['accent'],
  },
  'accent-foreground': {
    key: '{accent-foreground}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{accent-foreground}',
    },
    name: 'AccentForeground',
    attributes: {
      category: 'accent-foreground',
    },
    path: ['accent-foreground'],
  },
  destructive: {
    key: '{destructive}',
    value: '3 78% 46%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '3 78% 46%',
      type: 'color',
      key: '{destructive}',
    },
    name: 'Destructive',
    attributes: {
      category: 'destructive',
    },
    path: ['destructive'],
  },
  'destructive-foreground': {
    key: '{destructive-foreground}',
    value: '0 0% 100%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0% 100%',
      type: 'color',
      key: '{destructive-foreground}',
    },
    name: 'DestructiveForeground',
    attributes: {
      category: 'destructive-foreground',
    },
    path: ['destructive-foreground'],
  },
  input: {
    key: '{input}',
    value: '240 5% 91%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 91%',
      type: 'color',
      key: '{input}',
    },
    name: 'Input',
    attributes: {
      category: 'input',
    },
    path: ['input'],
  },
  ring: {
    key: '{ring}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{ring}',
    },
    name: 'Ring',
    attributes: {
      category: 'ring',
    },
    path: ['ring'],
  },
  radius: {
    key: '{radius}',
    value: '0.75rem',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0.75rem',
      type: 'dimension',
      key: '{radius}',
    },
    name: 'Radius',
    attributes: {
      category: 'radius',
    },
    path: ['radius'],
  },
  'chart-1': {
    key: '{chart-1}',
    value: '240 6% 10%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 6% 10%',
      type: 'color',
      key: '{chart-1}',
    },
    name: 'Chart1',
    attributes: {
      category: 'chart-1',
    },
    path: ['chart-1'],
  },
  'chart-2': {
    key: '{chart-2}',
    value: '142 71% 45%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '142 71% 45%',
      type: 'color',
      key: '{chart-2}',
    },
    name: 'Chart2',
    attributes: {
      category: 'chart-2',
    },
    path: ['chart-2'],
  },
  'chart-3': {
    key: '{chart-3}',
    value: '240 5% 45%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '240 5% 45%',
      type: 'color',
      key: '{chart-3}',
    },
    name: 'Chart3',
    attributes: {
      category: 'chart-3',
    },
    path: ['chart-3'],
  },
  'chart-4': {
    key: '{chart-4}',
    value: '3 78% 46%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '3 78% 46%',
      type: 'color',
      key: '{chart-4}',
    },
    name: 'Chart4',
    attributes: {
      category: 'chart-4',
    },
    path: ['chart-4'],
  },
  'chart-5': {
    key: '{chart-5}',
    value: '270 60% 55%',
    type: 'color',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '270 60% 55%',
      type: 'color',
      key: '{chart-5}',
    },
    name: 'Chart5',
    attributes: {
      category: 'chart-5',
    },
    path: ['chart-5'],
  },
  tremor: {
    brand: {
      faint: {
        key: '{tremor.brand.faint}',
        value: '240 5% 96%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 5% 96%',
          type: 'color',
          key: '{tremor.brand.faint}',
        },
        name: 'TremorBrandFaint',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'faint',
        },
        path: ['tremor', 'brand', 'faint'],
      },
      muted: {
        key: '{tremor.brand.muted}',
        value: '240 5% 90%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 5% 90%',
          type: 'color',
          key: '{tremor.brand.muted}',
        },
        name: 'TremorBrandMuted',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'muted',
        },
        path: ['tremor', 'brand', 'muted'],
      },
      subtle: {
        key: '{tremor.brand.subtle}',
        value: '240 5% 65%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 5% 65%',
          type: 'color',
          key: '{tremor.brand.subtle}',
        },
        name: 'TremorBrandSubtle',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'subtle',
        },
        path: ['tremor', 'brand', 'subtle'],
      },
      default: {
        key: '{tremor.brand.default}',
        value: '240 6% 10%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 10%',
          type: 'color',
          key: '{tremor.brand.default}',
        },
        name: 'TremorBrandDefault',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'default',
        },
        path: ['tremor', 'brand', 'default'],
      },
      emphasis: {
        key: '{tremor.brand.emphasis}',
        value: '0 0% 0%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '0 0% 0%',
          type: 'color',
          key: '{tremor.brand.emphasis}',
        },
        name: 'TremorBrandEmphasis',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'emphasis',
        },
        path: ['tremor', 'brand', 'emphasis'],
      },
      inverted: {
        key: '{tremor.brand.inverted}',
        value: '0 0% 100%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '0 0% 100%',
          type: 'color',
          key: '{tremor.brand.inverted}',
        },
        name: 'TremorBrandInverted',
        attributes: {
          category: 'tremor',
          type: 'brand',
          item: 'inverted',
        },
        path: ['tremor', 'brand', 'inverted'],
      },
    },
    background: {
      muted: {
        key: '{tremor.background.muted}',
        value: '240 5% 96%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 5% 96%',
          type: 'color',
          key: '{tremor.background.muted}',
        },
        name: 'TremorBackgroundMuted',
        attributes: {
          category: 'tremor',
          type: 'background',
          item: 'muted',
        },
        path: ['tremor', 'background', 'muted'],
      },
      subtle: {
        key: '{tremor.background.subtle}',
        value: '240 5% 92%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 5% 92%',
          type: 'color',
          key: '{tremor.background.subtle}',
        },
        name: 'TremorBackgroundSubtle',
        attributes: {
          category: 'tremor',
          type: 'background',
          item: 'subtle',
        },
        path: ['tremor', 'background', 'subtle'],
      },
      default: {
        key: '{tremor.background.default}',
        value: '0 0% 100%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '0 0% 100%',
          type: 'color',
          key: '{tremor.background.default}',
        },
        name: 'TremorBackgroundDefault',
        attributes: {
          category: 'tremor',
          type: 'background',
          item: 'default',
        },
        path: ['tremor', 'background', 'default'],
      },
      emphasis: {
        key: '{tremor.background.emphasis}',
        value: '240 6% 10%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 10%',
          type: 'color',
          key: '{tremor.background.emphasis}',
        },
        name: 'TremorBackgroundEmphasis',
        attributes: {
          category: 'tremor',
          type: 'background',
          item: 'emphasis',
        },
        path: ['tremor', 'background', 'emphasis'],
      },
    },
    border: {
      default: {
        key: '{tremor.border.default}',
        value: '240 6% 87%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 87%',
          type: 'color',
          key: '{tremor.border.default}',
        },
        name: 'TremorBorderDefault',
        attributes: {
          category: 'tremor',
          type: 'border',
          item: 'default',
        },
        path: ['tremor', 'border', 'default'],
      },
    },
    ring: {
      default: {
        key: '{tremor.ring.default}',
        value: '240 6% 10%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 10%',
          type: 'color',
          key: '{tremor.ring.default}',
        },
        name: 'TremorRingDefault',
        attributes: {
          category: 'tremor',
          type: 'ring',
          item: 'default',
        },
        path: ['tremor', 'ring', 'default'],
      },
    },
    content: {
      subtle: {
        key: '{tremor.content.subtle}',
        value: '240 3% 63%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 3% 63%',
          type: 'color',
          key: '{tremor.content.subtle}',
        },
        name: 'TremorContentSubtle',
        attributes: {
          category: 'tremor',
          type: 'content',
          item: 'subtle',
        },
        path: ['tremor', 'content', 'subtle'],
      },
      default: {
        key: '{tremor.content.default}',
        value: '240 3% 44%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 3% 44%',
          type: 'color',
          key: '{tremor.content.default}',
        },
        name: 'TremorContentDefault',
        attributes: {
          category: 'tremor',
          type: 'content',
          item: 'default',
        },
        path: ['tremor', 'content', 'default'],
      },
      emphasis: {
        key: '{tremor.content.emphasis}',
        value: '240 6% 23%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 23%',
          type: 'color',
          key: '{tremor.content.emphasis}',
        },
        name: 'TremorContentEmphasis',
        attributes: {
          category: 'tremor',
          type: 'content',
          item: 'emphasis',
        },
        path: ['tremor', 'content', 'emphasis'],
      },
      strong: {
        key: '{tremor.content.strong}',
        value: '240 6% 10%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '240 6% 10%',
          type: 'color',
          key: '{tremor.content.strong}',
        },
        name: 'TremorContentStrong',
        attributes: {
          category: 'tremor',
          type: 'content',
          item: 'strong',
        },
        path: ['tremor', 'content', 'strong'],
      },
      inverted: {
        key: '{tremor.content.inverted}',
        value: '0 0% 100%',
        type: 'color',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '0 0% 100%',
          type: 'color',
          key: '{tremor.content.inverted}',
        },
        name: 'TremorContentInverted',
        attributes: {
          category: 'tremor',
          type: 'content',
          item: 'inverted',
        },
        path: ['tremor', 'content', 'inverted'],
      },
    },
  },
  'shadow-card': {
    key: '{shadow-card}',
    value:
      '0 1px 2px rgba(0,0,0,0.02), 0 4px 12px rgba(0,0,0,0.03), 0 12px 32px rgba(0,0,0,0.03), 0 20px 48px rgba(0,0,0,0.04), inset 0 0 0 0.5px rgba(255, 255, 255, 0.7)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value:
        '0 1px 2px rgba(0,0,0,0.02), 0 4px 12px rgba(0,0,0,0.03), 0 12px 32px rgba(0,0,0,0.03), 0 20px 48px rgba(0,0,0,0.04), inset 0 0 0 0.5px rgba(255, 255, 255, 0.7)',
      type: 'shadow',
      key: '{shadow-card}',
    },
    name: 'ShadowCard',
    attributes: {
      category: 'shadow-card',
    },
    path: ['shadow-card'],
  },
  'shadow-card-hover': {
    key: '{shadow-card-hover}',
    value:
      '0 2px 4px rgba(0,0,0,0.02), 0 6px 16px rgba(0,0,0,0.04), 0 16px 40px rgba(0,0,0,0.04), 0 28px 64px rgba(0,0,0,0.05), inset 0 0 0 0.5px rgba(255, 255, 255, 0.8)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value:
        '0 2px 4px rgba(0,0,0,0.02), 0 6px 16px rgba(0,0,0,0.04), 0 16px 40px rgba(0,0,0,0.04), 0 28px 64px rgba(0,0,0,0.05), inset 0 0 0 0.5px rgba(255, 255, 255, 0.8)',
      type: 'shadow',
      key: '{shadow-card-hover}',
    },
    name: 'ShadowCardHover',
    attributes: {
      category: 'shadow-card-hover',
    },
    path: ['shadow-card-hover'],
  },
  'shadow-elevated': {
    key: '{shadow-elevated}',
    value:
      '0 2px 4px rgba(0,0,0,0.02), 0 8px 20px rgba(0,0,0,0.03), 0 20px 48px rgba(0,0,0,0.03), 0 32px 72px rgba(0,0,0,0.04), inset 0 0 0 0.5px rgba(255, 255, 255, 0.7)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value:
        '0 2px 4px rgba(0,0,0,0.02), 0 8px 20px rgba(0,0,0,0.03), 0 20px 48px rgba(0,0,0,0.03), 0 32px 72px rgba(0,0,0,0.04), inset 0 0 0 0.5px rgba(255, 255, 255, 0.7)',
      type: 'shadow',
      key: '{shadow-elevated}',
    },
    name: 'ShadowElevated',
    attributes: {
      category: 'shadow-elevated',
    },
    path: ['shadow-elevated'],
  },
  'shadow-glow-blue': {
    key: '{shadow-glow-blue}',
    value: '0 0 20px rgba(28, 28, 30, 0.18), 0 0 60px rgba(28, 28, 30, 0.06)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0 20px rgba(28, 28, 30, 0.18), 0 0 60px rgba(28, 28, 30, 0.06)',
      type: 'shadow',
      key: '{shadow-glow-blue}',
    },
    name: 'ShadowGlowBlue',
    attributes: {
      category: 'shadow-glow-blue',
    },
    path: ['shadow-glow-blue'],
  },
  'shadow-glow-primary': {
    key: '{shadow-glow-primary}',
    value: '0 0 20px rgba(28, 28, 30, 0.18), 0 0 60px rgba(28, 28, 30, 0.06)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0 20px rgba(28, 28, 30, 0.18), 0 0 60px rgba(28, 28, 30, 0.06)',
      type: 'shadow',
      key: '{shadow-glow-primary}',
    },
    name: 'ShadowGlowPrimary',
    attributes: {
      category: 'shadow-glow-primary',
    },
    path: ['shadow-glow-primary'],
  },
  'shadow-glow-electric': {
    key: '{shadow-glow-electric}',
    value: '0 0 24px rgba(28, 28, 30, 0.28), 0 0 80px rgba(28, 28, 30, 0.1)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 0 24px rgba(28, 28, 30, 0.28), 0 0 80px rgba(28, 28, 30, 0.1)',
      type: 'shadow',
      key: '{shadow-glow-electric}',
    },
    name: 'ShadowGlowElectric',
    attributes: {
      category: 'shadow-glow-electric',
    },
    path: ['shadow-glow-electric'],
  },
  'shadow-window': {
    key: '{shadow-window}',
    value:
      '0 2px 4px rgba(0,0,0,0.02), 0 8px 24px rgba(0,0,0,0.03), 0 24px 56px rgba(0,0,0,0.04), 0 40px 96px rgba(0,0,0,0.05), inset 0 0 0 0.5px rgba(255, 255, 255, 0.8)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value:
        '0 2px 4px rgba(0,0,0,0.02), 0 8px 24px rgba(0,0,0,0.03), 0 24px 56px rgba(0,0,0,0.04), 0 40px 96px rgba(0,0,0,0.05), inset 0 0 0 0.5px rgba(255, 255, 255, 0.8)',
      type: 'shadow',
      key: '{shadow-window}',
    },
    name: 'ShadowWindow',
    attributes: {
      category: 'shadow-window',
    },
    path: ['shadow-window'],
  },
  'shadow-diffusion-sm': {
    key: '{shadow-diffusion-sm}',
    value: '0 2px 4px -1px rgba(0, 0, 0, 0.04), 0 8px 12px -4px rgba(0, 0, 0, 0.03)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 2px 4px -1px rgba(0, 0, 0, 0.04), 0 8px 12px -4px rgba(0, 0, 0, 0.03)',
      type: 'shadow',
      key: '{shadow-diffusion-sm}',
    },
    name: 'ShadowDiffusionSm',
    attributes: {
      category: 'shadow-diffusion-sm',
    },
    path: ['shadow-diffusion-sm'],
  },
  'shadow-diffusion-md': {
    key: '{shadow-diffusion-md}',
    value: '0 3px 5px -1px rgba(0, 0, 0, 0.04), 0 14px 18px -5px rgba(0, 0, 0, 0.03)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 3px 5px -1px rgba(0, 0, 0, 0.04), 0 14px 18px -5px rgba(0, 0, 0, 0.03)',
      type: 'shadow',
      key: '{shadow-diffusion-md}',
    },
    name: 'ShadowDiffusionMd',
    attributes: {
      category: 'shadow-diffusion-md',
    },
    path: ['shadow-diffusion-md'],
  },
  'shadow-diffusion-lg': {
    key: '{shadow-diffusion-lg}',
    value: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 20px 25px -5px rgba(0, 0, 0, 0.03)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 20px 25px -5px rgba(0, 0, 0, 0.03)',
      type: 'shadow',
      key: '{shadow-diffusion-lg}',
    },
    name: 'ShadowDiffusionLg',
    attributes: {
      category: 'shadow-diffusion-lg',
    },
    path: ['shadow-diffusion-lg'],
  },
  'shadow-diffusion-xl': {
    key: '{shadow-diffusion-xl}',
    value: '0 4px 8px -2px rgba(0, 0, 0, 0.05), 0 28px 40px -8px rgba(0, 0, 0, 0.04)',
    type: 'shadow',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0 4px 8px -2px rgba(0, 0, 0, 0.05), 0 28px 40px -8px rgba(0, 0, 0, 0.04)',
      type: 'shadow',
      key: '{shadow-diffusion-xl}',
    },
    name: 'ShadowDiffusionXl',
    attributes: {
      category: 'shadow-diffusion-xl',
    },
    path: ['shadow-diffusion-xl'],
  },
  refraction: {
    'inner-border': {
      key: '{refraction.inner-border}',
      value: 'inset 0 1px 0 0 rgba(255, 255, 255, 0.9)',
      type: 'shadow',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'inset 0 1px 0 0 rgba(255, 255, 255, 0.9)',
        type: 'shadow',
        key: '{refraction.inner-border}',
      },
      name: 'RefractionInnerBorder',
      attributes: {
        category: 'refraction',
        type: 'inner-border',
      },
      path: ['refraction', 'inner-border'],
    },
    'inner-shadow': {
      key: '{refraction.inner-shadow}',
      value: 'inset 0 2px 8px rgba(0, 0, 0, 0.02)',
      type: 'shadow',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'inset 0 2px 8px rgba(0, 0, 0, 0.02)',
        type: 'shadow',
        key: '{refraction.inner-shadow}',
      },
      name: 'RefractionInnerShadow',
      attributes: {
        category: 'refraction',
        type: 'inner-shadow',
      },
      path: ['refraction', 'inner-shadow'],
    },
    'edge-light': {
      key: '{refraction.edge-light}',
      value: 'inset 0 0 0 1px rgba(255, 255, 255, 0.6)',
      type: 'shadow',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: 'inset 0 0 0 1px rgba(255, 255, 255, 0.6)',
        type: 'shadow',
        key: '{refraction.edge-light}',
      },
      name: 'RefractionEdgeLight',
      attributes: {
        category: 'refraction',
        type: 'edge-light',
      },
      path: ['refraction', 'edge-light'],
    },
  },
  wave: {
    intensity: {
      key: '{wave.intensity}',
      value: '0.2',
      type: 'number',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '0.2',
        type: 'number',
        key: '{wave.intensity}',
      },
      name: 'WaveIntensity',
      attributes: {
        category: 'wave',
        type: 'intensity',
      },
      path: ['wave', 'intensity'],
    },
    'speed-mult': {
      key: '{wave.speed-mult}',
      value: '0.5',
      type: 'number',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '0.5',
        type: 'number',
        key: '{wave.speed-mult}',
      },
      name: 'WaveSpeedMult',
      attributes: {
        category: 'wave',
        type: 'speed-mult',
      },
      path: ['wave', 'speed-mult'],
    },
    'ampl-scale': {
      key: '{wave.ampl-scale}',
      value: '0.4',
      type: 'number',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '0.4',
        type: 'number',
        key: '{wave.ampl-scale}',
      },
      name: 'WaveAmplScale',
      attributes: {
        category: 'wave',
        type: 'ampl-scale',
      },
      path: ['wave', 'ampl-scale'],
    },
    opacity: {
      key: '{wave.opacity}',
      value: '0.25',
      type: 'number',
      filePath: 'tokens.json',
      isSource: true,
      original: {
        value: '0.25',
        type: 'number',
        key: '{wave.opacity}',
      },
      name: 'WaveOpacity',
      attributes: {
        category: 'wave',
        type: 'opacity',
      },
      path: ['wave', 'opacity'],
    },
  },
  'radius-sm': {
    key: '{radius-sm}',
    value: '8px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '8px',
      type: 'dimension',
      key: '{radius-sm}',
    },
    name: 'RadiusSm',
    attributes: {
      category: 'radius-sm',
    },
    path: ['radius-sm'],
  },
  'radius-md': {
    key: '{radius-md}',
    value: '12px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '12px',
      type: 'dimension',
      key: '{radius-md}',
    },
    name: 'RadiusMd',
    attributes: {
      category: 'radius-md',
    },
    path: ['radius-md'],
  },
  'radius-lg': {
    key: '{radius-lg}',
    value: '16px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '16px',
      type: 'dimension',
      key: '{radius-lg}',
    },
    name: 'RadiusLg',
    attributes: {
      category: 'radius-lg',
    },
    path: ['radius-lg'],
  },
  'radius-xl': {
    key: '{radius-xl}',
    value: '24px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '24px',
      type: 'dimension',
      key: '{radius-xl}',
    },
    name: 'RadiusXl',
    attributes: {
      category: 'radius-xl',
    },
    path: ['radius-xl'],
  },
  'radius-card': {
    key: '{radius-card}',
    value: '20px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '20px',
      type: 'dimension',
      key: '{radius-card}',
    },
    name: 'RadiusCard',
    attributes: {
      category: 'radius-card',
    },
    path: ['radius-card'],
  },
  'radius-button': {
    key: '{radius-button}',
    value: '9999px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '9999px',
      type: 'dimension',
      key: '{radius-button}',
    },
    name: 'RadiusButton',
    attributes: {
      category: 'radius-button',
    },
    path: ['radius-button'],
  },
  'radius-full': {
    key: '{radius-full}',
    value: '9999px',
    type: 'dimension',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '9999px',
      type: 'dimension',
      key: '{radius-full}',
    },
    name: 'RadiusFull',
    attributes: {
      category: 'radius-full',
    },
    path: ['radius-full'],
  },
  motion: {
    duration: {
      instant: {
        key: '{motion.duration.instant}',
        value: '0ms',
        type: 'duration',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '0ms',
          type: 'duration',
          key: '{motion.duration.instant}',
        },
        name: 'MotionDurationInstant',
        attributes: {
          category: 'motion',
          type: 'duration',
          item: 'instant',
        },
        path: ['motion', 'duration', 'instant'],
      },
      fast: {
        key: '{motion.duration.fast}',
        value: '150ms',
        type: 'duration',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '150ms',
          type: 'duration',
          key: '{motion.duration.fast}',
        },
        name: 'MotionDurationFast',
        attributes: {
          category: 'motion',
          type: 'duration',
          item: 'fast',
        },
        path: ['motion', 'duration', 'fast'],
      },
      normal: {
        key: '{motion.duration.normal}',
        value: '250ms',
        type: 'duration',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '250ms',
          type: 'duration',
          key: '{motion.duration.normal}',
        },
        name: 'MotionDurationNormal',
        attributes: {
          category: 'motion',
          type: 'duration',
          item: 'normal',
        },
        path: ['motion', 'duration', 'normal'],
      },
      slow: {
        key: '{motion.duration.slow}',
        value: '400ms',
        type: 'duration',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '400ms',
          type: 'duration',
          key: '{motion.duration.slow}',
        },
        name: 'MotionDurationSlow',
        attributes: {
          category: 'motion',
          type: 'duration',
          item: 'slow',
        },
        path: ['motion', 'duration', 'slow'],
      },
      emphasis: {
        key: '{motion.duration.emphasis}',
        value: '600ms',
        type: 'duration',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: '600ms',
          type: 'duration',
          key: '{motion.duration.emphasis}',
        },
        name: 'MotionDurationEmphasis',
        attributes: {
          category: 'motion',
          type: 'duration',
          item: 'emphasis',
        },
        path: ['motion', 'duration', 'emphasis'],
      },
    },
    easing: {
      ease: {
        key: '{motion.easing.ease}',
        value: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
          type: 'cubicBezier',
          key: '{motion.easing.ease}',
        },
        name: 'MotionEasingEase',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'ease',
        },
        path: ['motion', 'easing', 'ease'],
      },
      'ease-out': {
        key: '{motion.easing.ease-out}',
        value: 'cubic-bezier(0, 0, 0.2, 1)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0, 0, 0.2, 1)',
          type: 'cubicBezier',
          key: '{motion.easing.ease-out}',
        },
        name: 'MotionEasingEaseOut',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'ease-out',
        },
        path: ['motion', 'easing', 'ease-out'],
      },
      'ease-in': {
        key: '{motion.easing.ease-in}',
        value: 'cubic-bezier(0.4, 0, 1, 1)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0.4, 0, 1, 1)',
          type: 'cubicBezier',
          key: '{motion.easing.ease-in}',
        },
        name: 'MotionEasingEaseIn',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'ease-in',
        },
        path: ['motion', 'easing', 'ease-in'],
      },
      'ease-in-out': {
        key: '{motion.easing.ease-in-out}',
        value: 'cubic-bezier(0.4, 0, 0.2, 1)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0.4, 0, 0.2, 1)',
          type: 'cubicBezier',
          key: '{motion.easing.ease-in-out}',
        },
        name: 'MotionEasingEaseInOut',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'ease-in-out',
        },
        path: ['motion', 'easing', 'ease-in-out'],
      },
      spring: {
        key: '{motion.easing.spring}',
        value: 'cubic-bezier(0.16, 1, 0.3, 1)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0.16, 1, 0.3, 1)',
          type: 'cubicBezier',
          key: '{motion.easing.spring}',
        },
        name: 'MotionEasingSpring',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'spring',
        },
        path: ['motion', 'easing', 'spring'],
      },
      bounce: {
        key: '{motion.easing.bounce}',
        value: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        type: 'cubicBezier',
        filePath: 'tokens.json',
        isSource: true,
        original: {
          value: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
          type: 'cubicBezier',
          key: '{motion.easing.bounce}',
        },
        name: 'MotionEasingBounce',
        attributes: {
          category: 'motion',
          type: 'easing',
          item: 'bounce',
        },
        path: ['motion', 'easing', 'bounce'],
      },
    },
  },
  'theme-transition-duration': {
    key: '{theme-transition-duration}',
    value: '0ms',
    type: 'duration',
    filePath: 'tokens.json',
    isSource: true,
    original: {
      value: '0ms',
      type: 'duration',
      key: '{theme-transition-duration}',
    },
    name: 'ThemeTransitionDuration',
    attributes: {
      category: 'theme-transition-duration',
    },
    path: ['theme-transition-duration'],
  },
}
