/**
 * generated.ts — AUTO-GENERATED. DO NOT EDIT.
 *
 * Generated by: packages/theme/scripts/generate-tokens.mjs
 * Source:       packages/theme/src/css/variables.css
 *
 * Re-run with: node packages/theme/scripts/generate-tokens.mjs
 * Or via Turbo: pnpm --filter @repo/theme codegen
 *
 * This file provides typed `var(--token)` references for use in:
 * - Framer Motion style props
 * - Canvas/WebGL drawing
 * - Runtime style injection
 *
 * For static Tailwind usage, use the className utilities instead
 * (e.g. `text-[var(--text-heading)]` or `shadow-card`).
 */

export const tokens = {
  color: {
    bg: {
      primary: 'var(--bg-primary)',
      secondary: 'var(--bg-secondary)',
      tertiary: 'var(--bg-tertiary)',
      buttonUiverse: 'var(--bg-button-uiverse)',
      buttonUiverseInner: 'var(--bg-button-uiverse-inner)',
    },
    border: {
      subtle: 'var(--border-subtle)',
      default: 'var(--border-default)',
      emphasis: 'var(--border-emphasis)',
    },
    text: {
      muted: 'var(--text-muted)',
      secondary: 'var(--text-secondary)',
      body: 'var(--text-body)',
      primary: 'var(--text-primary)',
      heading: 'var(--text-heading)',
      onGlass: 'var(--text-on-glass)',
      onGlassMuted: 'var(--text-on-glass-muted)',
      onGlassVideo: 'var(--text-on-glass-video)',
      onGlassVideoMuted: 'var(--text-on-glass-video-muted)',
      onDarkGlass: 'var(--text-on-dark-glass)',
      onDarkGlassMuted: 'var(--text-on-dark-glass-muted)',
    },
    accent: {
      red: 'var(--accent-red)',
      charcoal: 'var(--accent-charcoal)',
      blue: 'var(--accent-blue)',
      green: 'var(--accent-green)',
      electricBlue: 'var(--accent-electric-blue)',
      electricBlueHover: 'var(--accent-electric-blue-hover)',
      electricBlueSubtle: 'var(--accent-electric-blue-subtle)',
      electricBlueBorder: 'var(--accent-electric-blue-border)',
      mint: 'var(--accent-mint)',
      mintHover: 'var(--accent-mint-hover)',
      mintSubtle: 'var(--accent-mint-subtle)',
      mintBorder: 'var(--accent-mint-border)',
      amber: 'var(--accent-amber)',
      amberHover: 'var(--accent-amber-hover)',
      amberSubtle: 'var(--accent-amber-subtle)',
      amberBorder: 'var(--accent-amber-border)',
      foreground: 'var(--accent-foreground)',
    },
    mac: {
      red: 'var(--mac-red)',
      yellow: 'var(--mac-yellow)',
      green: 'var(--mac-green)',
      menuBarHeight: 'var(--mac-menu-bar-height)',
    },
    glass: {
      surface: 'var(--glass-surface)',
      surfaceHover: 'var(--glass-surface-hover)',
      surfaceStrong: 'var(--glass-surface-strong)',
      border: 'var(--glass-border)',
      borderTop: 'var(--glass-border-top)',
      videoSurface: 'var(--glass-video-surface)',
      videoSurfaceHover: 'var(--glass-video-surface-hover)',
      videoSurfaceStrong: 'var(--glass-video-surface-strong)',
      videoBackdrop: 'var(--glass-video-backdrop)',
      videoBorder: 'var(--glass-video-border)',
      videoBorderBottom: 'var(--glass-video-border-bottom)',
      videoSheen: 'var(--glass-video-sheen)',
      videoShadow: 'var(--glass-video-shadow)',
      videoRadius: 'var(--glass-video-radius)',
      premiumBackdrop: 'var(--glass-premium-backdrop)',
      premiumBorder: 'var(--glass-premium-border)',
      premiumRadius: 'var(--glass-premium-radius)',
    },
    vibrancy: {
      surface: 'var(--vibrancy-surface)',
      border: 'var(--vibrancy-border)',
    },
  },
  primitives: {
    arch0: '#ffffff',
    white: '#ffffff',
    arch1: '#ffffff',
    arch2: '#e8e8ed',
    arch3: '#d2d2d7',
    arch4: 'rgba(0, 0, 0, 0.06)',
    arch5: 'rgba(0, 0, 0, 0.12)',
    arch6: 'rgba(0, 0, 0, 0.2)',
    arch7: 'rgba(0, 0, 0, 0.3)',
    arch8: '#a1a1a6',
    arch9: '#6e6e73',
    arch10: '#3a3a3c',
    arch11: '#1d1d1f',
    arch12: '#d22118',
    arch13: '#1c1c1e',
    arch14: '#34c759',
    arch15: '#1c1c1e',
    archBrandBlue: '#1c1c1e',
    archBrandBlueHover: '#2c2c2e',
  },
  hsl: {
    background: '240 5% 96%',
    foreground: '240 6% 10%',
    card: '0 0% 100%',
    cardForeground: '240 6% 10%',
    popover: '0 0% 100%',
    popoverForeground: '240 6% 10%',
    primary: '240 6% 10%',
    primaryForeground: '0 0% 100%',
    secondary: '240 5% 91%',
    secondaryForeground: '240 6% 10%',
    muted: '240 5% 91%',
    mutedForeground: '240 3% 44%',
    accent: '240 5% 91%',
    accentForeground: '240 6% 10%',
    destructive: '3 78% 46%',
    destructiveForeground: '0 0% 100%',
    border: '240 6% 87%',
    input: '240 5% 91%',
    ring: '240 6% 10%',
    chart1: '240 6% 10%',
    chart2: '142 71% 45%',
    chart3: '240 5% 45%',
    chart4: '3 78% 46%',
    chart5: '270 60% 55%',
  },
  shadow: {
    glowElectricBlue: 'var(--shadow-glow-electric-blue)',
    glowMint: 'var(--shadow-glow-mint)',
    glowAmber: 'var(--shadow-glow-amber)',
    diffusionSm: 'var(--shadow-diffusion-sm)',
    diffusionMd: 'var(--shadow-diffusion-md)',
    diffusionLg: 'var(--shadow-diffusion-lg)',
    diffusionXl: 'var(--shadow-diffusion-xl)',
    glowBlue: 'var(--shadow-glow-blue)',
    glowPrimary: 'var(--shadow-glow-primary)',
    glowElectric: 'var(--shadow-glow-electric)',
    buttonUiverseAfter: 'var(--shadow-button-uiverse-after)',
    buttonUiverseBlob: 'var(--shadow-button-uiverse-blob)',
    cirTabs: 'var(--shadow-cir-tabs)',
    cirCheckFocus: 'var(--shadow-cir-check-focus)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  radius: {},
  wave: {
    intensity: '0.2',
    speedMult: '0.5',
    amplScale: '0.4',
    opacity: '0.25',
  },
} as const

export type Tokens = typeof tokens
export type ColorTokens = typeof tokens.color
export type PrimitiveTokens = typeof tokens.primitives
export type HslTokens = typeof tokens.hsl
export type ShadowTokens = typeof tokens.shadow
export type RadiusTokens = typeof tokens.radius
